name: ninja_ed25519
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/ninja-dart/ninja_ed25519

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  collection: ^1.15.0
  ninja: ^3.0.5

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.11
